### ISSUE TITLE
Not an issue, but a thank you.

### ISSUE THREAD

**Issue by Oberfail** [Akaczer/annie-dark-bootleg-version#1]
Hey, i really missed the annie dark theme. Thanks for recreating it, my eyes and i really appreciate it :)

I have no idea where else to write you, so feel free to close the "issue".

**Comment by Akaczer** [comment]
No problem! 
Better Discord declined my theme, so I didn't expect anyone to find it. I mainly made it for me and my friends, and I just added it to GitHub to make updating it easier, but you can use it too. Feel free to tell me if something is broken or if you feel like something should look different (I had only a few screenshots, so I had to improvise).
